[package]
name = "the-random-bot-rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#serenity = { default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
rand = "0.8.4"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
poise = "0.3.0"
dotenv = "0.15.0"
wikipedia = "0.3.4"